[supervisord]
## for Docker Culture
pidfile=/tmp/supervisord.pid
# log -> watch docker log <container>
logfile=/dev/stdout
logfile_maxbytes=0

## postStartCommand must be ended immediately
nodaemon=false
## CMD ["supervisord"] must need daemon
# nodaemon=true


[unix_http_server]
file=/var/run/supervisor/supervisor.sock
chmod=0777

[program:jupyter_notebook]
command=jupyter notebook --no-browser --allow-root --ip=0.0.0.0 --port=8888 --NotebookApp.token=''
autostart=true
autorestart=true
# stdout_logfile=/var/log/supervisor/jupyter.log
# stderr_logfile=/var/log/supervisor/jupyter_err.log
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
