version: "3.8"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    # 認証系オプションはcomposeで制御
    command:
      [
        "--ip=0.0.0.0",
        "--port=8888",
        "--NotebookApp.token=''"
      ]
    hostname: note-server
    networks:
      - jupyter_nw
    ports:
      - target: 8888
        published: 8888
    volumes:
      - type: bind
        source: ../
        target: /workspace

networks:
  jupyter_nw:
